### ISSUE TITLE
ScrollView is not worked on FadeView

### ISSUE THREAD

**Issue by tikkichan4** [n4kz/react-native-fade-view#2]
I am currently using FadeView with two child ScrollView. The crossfade effect worked but the second ScrollView made the first ScrollView not worked.

The second ScrollView is invisible, but still not in-touchable when action={false}.
My idea for fixing the bug should be Scale / Move / set the z-index of the component while transiting. Hope my ideas help !

**Comment by n4kz** [comment]
Thanks for reporting!

Fixed by adding `pointerEvents` prop to child containers. Now inactive views will not receive pointer events and everything should work as expected. Released in `0.3.0`.
