### ISSUE TITLE
Continuous ripple?

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-fade-view#4]
Hi there, I was wondering where you got that continuous ripple animation? I was making a "recording" app and needed such a ripple. Thanks! I tried this here - https://github.com/n4kz/react-native-material-ripple - but this is not a continuous like "audio record" kind of ripple.

**Comment by n4kz** [comment]
Thanks for question, please take look at https://github.com/n4kz/react-native-indicators for infinite animations. `WaveIndicator` was used for example project in this package.

**Comment by Noitidart** [comment]
Oh thank you very much!!
